language: zh

pipeline:
  - name: "MitieNLP"
    model: "data/total_word_feature_extractor_zh.dat"
  - name: "JiebaTokenizer"
    dictionary_path: "./jieba_userdict" 
  - name: "MitieEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "RegexFeaturizer"
  - name: "MitieFeaturizer"
  - name: "SklearnIntentClassifier"
  
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.3
    core_threshold: 0.3
    #fallback_core_action_name: "action_ask_affirmation"
    #fallback_nlu_action_name: "action_ask_affirmation"
    #deny_suggestion_intent_name: "out_of_scope"